Tagline0: I'm a programmer
Tagline1: Hello
Tagline2: I'm Daniel
Tagline3: I'm Daniel, and..

GoTop: Top

NavAbout: About
NavSkills: Skills
NavExperiments: Experiments
NavContact: Contact me!

Toolset: Toolset
ToolsetVim: The text editor that teaches me something new everyday!
ToolsetAg: One of the best code search tools! It saved me countless hours!
ToolsetGit: Who's not using version control nowadays?
ToolsetArch: My development OS of choice!

SkillsProfessional: Professional
SkillsPersonal: Personal

ExperimentTechnologies: Technologies used:
ExperimentsWhat: What I learnt?

ContactMessage: Need a freelancer? An employee? A consultant? Whatever you need, let me know!
ContactName: Your name
ContactEmail: Your email
ContactTitle: Title
ContactContent: Tell me what you need!
