LangLabel: Language
LangSwitchButton: Switch

Tagline0: I'm a programmer
Tagline1: Hello
Tagline2: I'm Daniel
Tagline3: I'm Daniel, and..

GoTop: Top

NavAbout: About
NavSkills: Skills
NavExperiments: Experiments
NavContact: Contact me!

Dotfiles: For more information about my development environment, you can check my

ViewOnGithub: View on Github

ContactMessage: Need a freelancer? An employee? A consultant? Whatever you need, let me know!
ContactName: Name
ContactEmail: Email
ContactTitle: Title
ContactContent: Tell me what you need!
ContactSend: Send

MailSent: Your email has been sent!
MailError: There was an error validating the contact form
MailServerError: Server error sending email

IconsBy: Icons by
