LangLabel: Language
LangSwitchButton: Switch

Tagline0: I'm a programmer
Tagline1: Hello
Tagline2: I'm Daniel
Tagline3: I'm Daniel, and..

GoTop: Top

NavAbout: About
NavSkills: Skills
NavExperiments: Experiments
NavContact: Contact me!

Toolset: Essential tools
ToolsetVim: The text editor that teaches me something new everyday!
ToolsetAg: One of the best code search tools! It saved me countless hours!
ToolsetGit: Who's not using version control nowadays?
ToolsetArch: My development OS of choice!
ToolsetDotfiles: If you are interested check my

SkillsProfessional: Professional
SkillsFullstack: Full-stack development
SkillsFullstackContent: Front-end development, back-end development, API design and development, databases design and development, deployment.
SkillsProgramming: C++ / Java / Python / Haskell
SkillsProgrammingContent: Code analysis, optimization and development.
SkillsDesign: UX Design
SkillsDesignContent: Minimal yet comprehensive interfaces are my best bet.

SkillsPersonal: Personal
SkillsTeam: Team Player
SkillsTeamContent: I have been part of different development teams. Some of the  products made include applications, websites and games.
SkillsIdeas: Open to new ideas!
SkillsIdeasContent: I love learning new stuff everyday, whether by myself or from other people.

ViewOnGithub: View on Github

ContactMessage: Need a freelancer? An employee? A consultant? Whatever you need, let me know!
ContactName: Name
ContactEmail: Email
ContactTitle: Title
ContactContent: Tell me what you need!
ContactSend: Send

MailSent: Your email has been sent!
MailError: There was an error validating the contact form
MailServerError: Server error sending email

IconsBy: Icons by
