LangSwitchButton: Cambiar

Tagline0: Soy un programador
Tagline1: Hola
Tagline2: Soy Daniel
Tagline3: Soy Daniel, y..

GoTop: Arriba

NavAbout: Acerca de mi
NavSkills: Habilidades
NavExperiments: Experimentos
NavContact: Contáctame

Toolset: Herramientas
ToolsetVim: El editor de texto que me enseña algo nuevo cada día!
ToolsetAg: Uno de los mejores buscadores de código. Me ha ahorrado muchas horas de trabajo!
ToolsetGit: Quién no está usando control de versiones hoy en día?
ToolsetArch: Mi entorno de desarrollo preferido.
ToolsetDotfiles: Si estas interesado puedes ver mis

SkillsProfessional: Profesional
SkillsFullstack: Desarrollo Full-stack
SkillsFullstackContent: Front-end, back-end, APIs, bases de datos y despliegue.
SkillsProgramming: C++ / Java / Python / Haskell
SkillsProgrammingContent: Análisis, optimización y desarrollo.
SkillsDesign: UX Design
SkillsDesignContent: Me especializo en el diseño minimal.

SkillsPersonal: Personal
SkillsTeam: Jugador de equipo
SkillsTeamContent: He sido parte de varios equipos de desarrollo. Varios de los productos que se desarrollaron incluyen aplicaciones, sitios web y juegos.
SkillsIdeas: Abierto a nuevas ideas!
SkillsIdeasContent: Me encanta aprender cosas nuevas todos los dias, ya sea por mi mísmo o a través de otras personas.

ViewOnGithub: Ver en Github

ContactMessage: Necesitas un freelancer? Un empleado? Un consultor? Sea lo que sea, házmelo saber!
ContactName: Nombre
ContactEmail: Corre electrónico
ContactTitle: Título
ContactContent: Dime lo que necesitas!
ContactSend: Enviar

MailSent: Su correo a sido enviado!
MailError: Ha ocurrido un error validando el formulario de contacto
MailServerError: Error en el servidor enviando correo

IconsBy: Iconos cortesía de
