Tagline0: Soy un programador
Tagline1: Hola
Tagline2: Soy Daniel
Tagline3: Soy Daniel, y..

GoTop: Volver arriba

NavAbout: Acerca de mi
NavSkills: Habilidades
NavExperiments: Experimentos
NavContact: Contáctame

Toolset: Herramientas
ToolsetVim: El editor de texto que me enseña algo nuevo cada día!
ToolsetAg: Uno de los mejores buscadores de código. Me ha ahorrado muchas horas de trabajo!
ToolsetGit: Quién no está usando control de versiones hoy en día?
ToolsetArch: My SO para desarrollo

SkillsProfessional: Profesional
SkillsPersonal: Personal

ExperimentTechnologies: Tecnologías usadas:
ExperimentsWhat: Qué aprendí?

ContactMessage: Necesita un freelancer? Un empleado? Un consultor? Sea lo que sea, hagámelo saber!
ContactName: Tu nombre
ContactEmail: Corre electrónico
ContactTitle: Título
ContactContent: Dime lo que necesitas!
