LangLabel: Idioma
LangSwitchButton: Cambiar

Tagline0: Soy un programador
Tagline1: Hola
Tagline2: Soy Daniel
Tagline3: Soy Daniel, y..

GoTop: Arriba

NavAbout: Acerca de mi
NavSkills: Habilidades
NavExperiments: Experimentos
NavContact: Contáctame

Dotfiles: Para más información acerca de mi entorno de desarrolo, puedes ver mis

ViewOnGithub: Ver en Github

ContactMessage: Necesitas un freelancer? Un empleado? Un consultor? Sea lo que sea, házmelo saber!
ContactName: Nombre
ContactEmail: Corre electrónico
ContactTitle: Título
ContactContent: Dime lo que necesitas!
ContactSend: Enviar

MailSent: Su correo a sido enviado!
MailError: Ha ocurrido un error validando el formulario de contacto
MailServerError: Error en el servidor enviando correo

IconsBy: Iconos por
