# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

# Environment variables for deployment in OpenShift
static-dir:     "_env:OPENSHIFT_DIY_STATIC_DIR:static"
host:           "_env:OPENSHIFT_DIY_IP:*4" # any IPv4 host
port:           "_env:OPENSHIFT_DIY_PORT:3000"
approot:        "_env:OPENSHIFT_DIY_URL:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Extra settings for Mailgun contact form
mail-send-to: "_env:MAILGUN_TO:ers.daniel+portfolio@gmail.com"
mail-api-key: "_env:MAILGUN_API_KEY:123abc"
mail-domain: "_env:MAILGUN_DOMAIN:sandbox.mailgun.org"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
    database: "_env:SQLITE_DATABASE:/tmp/Portfolio.sqlite3"
    poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Copyright © 2015, Daniel Rivas
#analytics: UA-YOURCODE
