# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:OPENSHIFT_DIY_STATIC_DIR:static"
host:           "_env:OPENSHIFT_DIY_URL:*4" # any IPv4 host
port:           "_env:OPENSHIFT_DIY_PORT:8080"
approot:        "_env:OPENSHIFT_DIY_URL:http://localhost:8080"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  database: "_env:SQLITE_DATABASE:Portfolio.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Copyright © 2015, Daniel Rivas
#analytics: UA-YOURCODE
